<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ccdo="urn:EEC:M:ComplexDataObjects:v0.4.12" xmlns:csdo="urn:EEC:M:SimpleDataObjects:v0.4.12" xmlns:doc="urn:EEC:R:SM:SS:08:DangerousProductAlert:v1.0.0" xmlns:smcdo="urn:EEC:M:SM:ComplexDataObjects:v0.3.9" xmlns:smsdo="urn:EEC:M:SM:SimpleDataObjects:v0.3.9" elementFormDefault="qualified" targetNamespace="urn:EEC:R:SM:SS:08:DangerousProductAlert:v1.0.0" version="1.0.0">
    <xs:import namespace="urn:EEC:M:SimpleDataObjects:v0.4.12" schemaLocation="EEC_M_SimpleDataObjects_v0.4.12.xsd"/>
    <xs:import namespace="urn:EEC:M:ComplexDataObjects:v0.4.12" schemaLocation="EEC_M_ComplexDataObjects_v0.4.12.xsd"/>
    <xs:import namespace="urn:EEC:M:SM:SimpleDataObjects:v0.3.9" schemaLocation="EEC_M_SM_SimpleDataObjects_v0.3.9.xsd"/>
    <xs:import namespace="urn:EEC:M:SM:ComplexDataObjects:v0.3.9" schemaLocation="EEC_M_SM_ComplexDataObjects_v0.3.9.xsd"/>
    <!--содержит сведения о случае обнаружения на территориях государств-членов продукции ненадлежащего качества-->
    <!-- R.SM.SS.08.002.NSP: Сведения об обнаружении опасной продукции и принятых санитарных мерах (Сведения об обнаружении опасной продукции и принятых санитарных мерах) -->
    <!-- R.SM.SS.08.002: Сведения об обнаружении опасной продукции и принятых санитарных мерах (Сведения об обнаружении опасной продукции и принятых санитарных мерах. Детали) -->
    <xs:element name="DangerousProductAlertDetails" type="doc:DangerousProductAlertDetailsType">
        <xs:annotation>
            <xs:documentation>Содержит сведения о случаях обнаружения на территориях государств – членов Союза продукции, опасной для жизни, здоровья человека и среды его обитания, а также о принятых санитарных мерах</xs:documentation>
        </xs:annotation>
    </xs:element>
    <!-- R.SM.SS.08.002.CDT: Сведения об обнаружении опасной продукции и принятых санитарных мерах (Сведения об обнаружении опасной продукции и принятых санитарных мерах_ Детали. Тип) -->
    <xs:complexType name="DangerousProductAlertDetailsType">
        <xs:annotation>
            <xs:documentation>содержит сведения о случае обнаружения на территориях государств-членов продукции, опасной для жизни и здоровья человека, а также о принятых санитарных мерах</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element ref="ccdo:EDocHeader"/>
            <xs:element maxOccurs="unbounded" ref="smcdo:DangerousProductAlertDetails"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
