<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ccdo="urn:EEC:M:ComplexDataObjects:v0.4.12" xmlns:csdo="urn:EEC:M:SimpleDataObjects:v0.4.12" xmlns:doc="urn:EEC:R:ProcessingResultDetails:v1.0.7" elementFormDefault="qualified" targetNamespace="urn:EEC:R:ProcessingResultDetails:v1.0.7" version="1.0.7">
    <xs:import namespace="urn:EEC:M:SimpleDataObjects:v0.4.12" schemaLocation="EEC_M_SimpleDataObjects_v0.4.12.xsd"/>
    <xs:import namespace="urn:EEC:M:ComplexDataObjects:v0.4.12" schemaLocation="EEC_M_ComplexDataObjects_v0.4.12.xsd"/>
    <!--R.006.NSP: - (-) -->
    <!-- R.006: Уведомление о результате обработки (Уведомление о результате обработки. Детали) -->
    <xs:element name="ProcessingResultDetails" type="doc:ProcessingResultDetailsType">
        <xs:annotation>
            <xs:documentation>Сведения о результате обработки запроса респондентом</xs:documentation>
        </xs:annotation>
    </xs:element>
    <!-- R.006.CDT: Уведомление о результате обработки (Уведомление о результате обработки_ Детали. Тип) -->
    <xs:complexType name="ProcessingResultDetailsType">
        <xs:annotation>
            <xs:documentation>Компоненты, представляющие детализированную информацию о результате обработки</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element ref="ccdo:EDocHeader"/>
            <xs:element ref="csdo:EventDateTime">
                <xs:annotation>
                    <xs:documentation>Дата и время окончания обработки сведений</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element ref="csdo:ProcessingResultV2Code"/>
            <xs:element minOccurs="0" ref="csdo:DescriptionText">
                <xs:annotation>
                    <xs:documentation>Описание результата обработки сведений в произвольной форме</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
